name: Compile LaTeX Document

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    compile:
        runs-on: ubuntu-latest
    
        steps:
            - name: Get current date
              id: date
              run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up TeX Live
              uses: xu-cheng/latex-action@v2
              with:
                root_file: main.tex
            
            - name: Upload PDF
              uses: actions/upload-artifact@v4
              with:
                name: document-${{ env.NOW }}.pdf
                path: main.pdf